### ISSUE TITLE
improve package name 

### ISSUE THREAD

**Issue by sonygod** [PeyTy/LuaXe#43]
improve package name 

haxe code with -lib HUGS

    package ;
    import unityengine.Debug;
    import unityengine.PrimitiveType;
    import unityengine.GameObject;
    import unityengine.MonoBehaviour;
    import unityengine.Vector3;
    
    class Main extends MonoBehaviour
    {
    public static function main()
    {
       GameObject.CreatePrimitive(PrimitiveType.Cube);
    
    // Multiline strings are supported
      Debug.Log('fuck');
    		 
    }
    	
    	function Start():Void {
    		gameObject.transform.position = new Vector3(1, 1, 1);
    	}
    }

and the luaxe

    Main_Main = {};
    ___inherit(Main_Main, unityengine_MonoBehaviour_MonoBehaviour);
    Main_Main.__name__ = "Main_Main";
    Main_Main.__index = Main_Main;
    	
    	function Main_Main.new()
    		local self = setmetatable({ }, Main_Main)
    				___inherit(self, unityengine_MonoBehaviour_MonoBehaviour.new())
    		return self
    	end
    	function Main_Main.main()
    		unityengine_GameObject_GameObject.CreatePrimitive(unityengine_PrimitiveType_PrimitiveType.Cube);
    		unityengine_Debug_Debug.Log("fuck")
    	end
    	function Main_Main:Start()
    		self.gameObject.transform.position = unityengine_Vector3_Vector3.new(1, 1, 1)
    	end
    	
    	
    Main_Main.__props__ = {};

I want to ask can it replace  unityengine_Vector3_Vector3 to  Vector3 ?

**Comment by PeyTy** [comment]
@sonygod `@nonew` meta is implemented. Details: https://github.com/PeyTy/LuaXe/blob/master/README.md#external-classes-usage
