### ISSUE TITLE
package name issue

### ISSUE THREAD

**Issue by sonygod** [PeyTy/LuaXe#48]
package ;

import unityengine.Debug;

class Test2 extends Test1 
{

	public function new() 
	{
		super();
		
	}
	
	override public function test() 
	{
		super.test();
		Debug.Log("2015");
		
	}
	
}

and the  lua file

unityengine_Debug_Debug.Log("2015")

can I only out Debug.Log("2015") instead of unityengine_Debug_Debug.Log("2015")?

it's seem not support 'native' 

package unityengine;

@:native("Debug") @:final
extern class Debug extends Object

**Comment by PeyTy** [comment]
@sonygod must now work as expected
