### ISSUE TITLE
std Xml support

### ISSUE THREAD

**Issue by jdonaldson** [PeyTy/LuaXe#58]
This would be nice to have.  We could get most of the std implementation working if #56 and #57 get fixed.  I could write it up.

For what it's worth, I also see that @Simn is working on an improved xml parser:
https://github.com/HaxeFoundation/haxe/pull/3752

That would be nice to support as well... However, I'm having trouble getting Luaxe to work with the latest Haxe nightlies... have you had a chance to try those?

**Comment by PeyTy** [comment]
@jdonaldson Hello, Justin! New Haxe versions are something buggy and new Std classes have breaking compatibility changes. I am waiting for any "stable" or release versions.

Most issues are Lua language limitations, and I am finding a not-so-dirty hacks to bypass them.
This takes much time.

When LuaXe would fully mimic js target behaviour and language features - there wouldn't any problems to use any XML parser that is compatible with JS.

**Comment by jdonaldson** [comment]
I understand, thanks for your work!

**Comment by jdonaldson** [comment]
I'm closing this, I see the Xml feature further down the list of issues here.
