### ISSUE TITLE
[QUESTION] lua with haxe/flixel

### ISSUE THREAD

**Issue by lewislepton** [PeyTy/LuaXe#68]
hello,

just spotted this. mainly because i want to use lua instead. prefer it rather than AS3, or whatever the language is, which is HAXE. just seems really weird.
but was just to ask about HAXEFLIXEL, and how luaxe deals with it, if at all.
im interested in this, since i dont want to realy use the HAXE language, but love what you can do

also is it worth waiting until the next big update of luaxe bfore i start using since it seems the code base will change for the better?

many thanks

**Comment by PeyTy** [comment]
Hello @lewislepton ! We now rewriting LuaXe into OCaml to make it official Haxe target.
If you don`t want to rebuild Haxe with Lua support - any of this https://github.com/PeyTy/haxe or (recommended) this https://github.com/jdonaldson/haxe/tree/haxe_lua_rb2
you can keep using LuaXe *with Haxe 3.1.3* ! (Haxe 3.2 is broken).

About Flixel: currently there isn't Lua-to-Flixel bindings, but someone are trying to implement part of them here https://github.com/lua-alchemy/lua-alchemy/issues/149 
You could ask him.

About Lua: if you prefer Lua much more than give a try to http://www.cocos2d-x.org/products#cocos2d-x
it contatins full Lua support (just scroll page a little down).

**Comment by lewislepton** [comment]
cool spot. cheers for getting back.
good about the flixel stuff. would be nice to see that

well ive looked cocos2d, but thats not for me. i thought it was, but no ;)
i am working with other lua based things though. but thank you. i may give it another go, maybe ;)
